# Generated by Django 5.1.7 on 2025-03-22 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('C', 'Consulta'), ('S', 'Servicio'), ('T', 'Tratamiento'), ('E', 'Estudios'), ('L', 'Laboratorio')], max_length=50, verbose_name='Tipo de Cita')),
                ('doctor_number', models.IntegerField(verbose_name='Número de médico que asiste')),
                ('appointment_date', models.DateTimeField(verbose_name='Fecha y hora de la Cita')),
                ('status', models.CharField(default='Activa', max_length=100, verbose_name='Estatus de Cita')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
        ),
    ]
