# Generated by Django 5.1.7 on 2025-03-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalappointment',
            name='doctor_number',
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='doctor_name',
            field=models.CharField(default='Testing', max_length=100, verbose_name='Nombre de médico que asiste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='patient',
            field=models.CharField(max_length=150, verbose_name='Paciente'),
        ),
    ]
